# Generated by Django 5.0.2 on 2024-02-13 04:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0003_alter_dndcharacter_spells'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dndcharacter',
            name='speed',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(30)]),
        ),
    ]
