# Generated by Django 5.0.2 on 2024-02-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonsterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monster_name', models.CharField(help_text='Enter a Monster Name', max_length=50, unique=True)),
            ],
            options={
                'ordering': ['-monster_name'],
            },
        ),
    ]
