# Generated by Django 5.0.2 on 2024-02-11 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monsters', '0003_armor_meta_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npc', models.CharField(help_text='NPC field. Example: Villager', max_length=100)),
            ],
            options={
                'ordering': ['-npc'],
            },
        ),
        migrations.RenameModel(
            old_name='Meta_Description',
            new_name='Item',
        ),
        migrations.DeleteModel(
            name='Armor',
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-item']},
        ),
        migrations.RenameField(
            model_name='item',
            old_name='meta_description',
            new_name='item',
        ),
    ]
